"""baseline - eingefrorener Schemastand bei Einfuehrung von Alembic (2026-08-31)

Autogeneriert gegen eine leere DB aus `models.Base.metadata` in dem Zustand,
den die bestehende Produktions-DB (aufgebaut per altem create_all +
ensure_columns) zu diesem Zeitpunkt hatte.

`app/db_migrate.run_migrations` STEMPELT bestehende Installationen ohne
`alembic_version` auf diese Revision (die Tabellen sind dort ja schon da) und
faehrt danach die folgenden Revisionen. Nur eine wirklich leere DB fuehrt
`upgrade()` hier tatsaechlich aus.

Ab hier: Schema-Aenderungen als neue Revision
(`cd backend && alembic revision --autogenerate -m "..."`), keine neuen
`ensure_columns`-Zeilen in main.py.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-31
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'snoozed', name='assistantsuggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_id', name='uq_assistant_suggestion_kind_ref')
    )
    with op.batch_alter_table('assistant_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_suggestions_id'), ['id'], unique=False)

    op.create_table('basiszins_rates',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rate_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('calendar_url', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('pending_delete', sa.Boolean(), nullable=False),
    sa.Column('travel_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('rrule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_uid'), ['uid'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('einnahme', 'ausgabe', name='categorytype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('gewicht', 'schlaf', 'schritte', 'puls', name='healthmetrictype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_type', 'date', name='uq_health_metric_type_date')
    )
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_metrics_id'), ['id'], unique=False)

    op.create_table('immich_quality_flags',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at_immich', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('isin_ticker_cache',
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    op.create_table('life_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('check_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminded_date', sa.Date(), nullable=True),
    sa.Column('target_days_per_week', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_areas_id'), ['id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_id'), ['id'], unique=False)

    op.create_table('price_history_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('range_key', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'symbol', 'range_key', name='uq_price_cache')
    )
    with op.batch_alter_table('price_history_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_cache_id'), ['id'], unique=False)

    op.create_table('proactive_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proactive_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proactive_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proactive_feedback_id'), ['id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_id'), ['id'], unique=False)

    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weekdays', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('items_text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_id'), ['id'], unique=False)

    op.create_table('smarthome_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smarthome_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smarthome_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_smarthome_actions_id'), ['id'], unique=False)

    op.create_table('smarthome_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smarthome_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smarthome_aliases_id'), ['id'], unique=False)

    op.create_table('smarthome_automation_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_json', sa.Text(), nullable=True),
    sa.Column('yaml_text', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ha_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smarthome_automation_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smarthome_automation_drafts_id'), ['id'], unique=False)

    op.create_table('smarthome_floorplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_tombstones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_tombstones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_tombstones_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_tombstones_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_tombstones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_tombstones_space_id'), ['space_id'], unique=False)

    op.create_table('tax_tip_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tip_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'tip_id', name='uq_tax_tip_year')
    )
    with op.batch_alter_table('tax_tip_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_tip_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_tip_status_year'), ['year'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('pending_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_uid'), ['uid'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_set_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret_encrypted', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('totp_recovery_code_hash', sa.String(), nullable=True),
    sa.Column('session_idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_locked_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('check_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminded_date', sa.Date(), nullable=True),
    sa.Column('auto_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_auto_check_at', sa.DateTime(), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_id'), ['id'], unique=False)

    op.create_table('category_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=False),
    sa.Column('new_category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_corrections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_corrections_merchant_key'), ['merchant_key'], unique=False)

    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rules_id'), ['id'], unique=False)

    op.create_table('life_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['life_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_checkins_id'), ['id'], unique=False)

    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'meal', name='uq_mealplan_date_meal')
    )
    with op.batch_alter_table('meal_plan_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_entries_id'), ['id'], unique=False)

    op.create_table('passkey_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passkey_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkey_credentials_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_passkey_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_passkey_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('routine_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('checked_items_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'date', name='uq_routine_run_date')
    )
    with op.batch_alter_table('routine_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_runs_id'), ['id'], unique=False)

    op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_digest_net_worth', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaces_owner_id'), ['owner_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('girokonto', 'bargeld', 'sparkonto', 'tagesgeldkonto', 'depot', 'sonstiges', name='accounttype'), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('dispo_alert_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    op.create_table('bitvavo_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_secret_encrypted', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitvavo_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitvavo_connections_id'), ['id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'category_id', name='uq_budget_space_category')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_id'), ['id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('goal_type', sa.Enum('auto_financial', 'manual', name='goaltype'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', 'archived', name='goalstatus'), nullable=False),
    sa.Column('predecessor_goal_id', sa.Integer(), nullable=True),
    sa.Column('completion_seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('aktie', 'etf', 'anleihe', 'krypto', 'sonstiges', name='assettype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_dividend_notified_for', sa.Date(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_id'), ['id'], unique=False)

    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('accounts_total', sa.Float(), nullable=False),
    sa.Column('investments_total', sa.Float(), nullable=False),
    sa.Column('debts_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'date', name='uq_net_worth_snapshot_space_date')
    )
    with op.batch_alter_table('net_worth_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_net_worth_snapshots_id'), ['id'], unique=False)

    op.create_table('notified_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notified_anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notified_anomalies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notified_anomalies_key'), ['key'], unique=False)

    op.create_table('savings_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('dynamization_rate', sa.Float(), nullable=True),
    sa.Column('next_execution_date', sa.Date(), nullable=True),
    sa.Column('security_type', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'isin', name='uq_savings_plan_isin')
    )
    with op.batch_alter_table('savings_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_plans_id'), ['id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_id'), ['id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_3d_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('category_spend_above', 'account_balance_below', 'category_deviation', 'goal_progress_above', name='alertruletype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_id'), ['id'], unique=False)

    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('blz', sa.String(), nullable=False),
    sa.Column('fints_url', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('pin_encrypted', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_connections_id'), ['id'], unique=False)

    op.create_table('business_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('check_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminded_date', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_projects_id'), ['id'], unique=False)

    op.create_table('contract_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('auto_advance_frequency', sa.String(), nullable=True),
    sa.Column('last_reminded_for', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('should_cancel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'description_key', name='uq_contract_reminder_account_desc')
    )
    with op.batch_alter_table('contract_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_reminders_id'), ['id'], unique=False)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('annuitaeten', 'raten', 'endfaellig', 'dispo', 'privat', name='debtkind'), nullable=False),
    sa.Column('lender', sa.String(), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('interest_rate_percent', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('interest_fixed_until', sa.Date(), nullable=True),
    sa.Column('follow_up_interest_rate_percent', sa.Float(), nullable=True),
    sa.Column('commitment_rate_percent', sa.Float(), nullable=True),
    sa.Column('commitment_free_months', sa.Integer(), nullable=True),
    sa.Column('undisbursed_amount', sa.Float(), nullable=True),
    sa.Column('upfront_fees', sa.Float(), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('monthly_insurance', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paid_off', name='debtstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_id'), ['id'], unique=False)

    op.create_table('ebay_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ebay_username', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ebay_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ebay_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ebay_connections_state'), ['state'], unique=True)

    op.create_table('enablebanking_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('aspsp_name', sa.String(), nullable=False),
    sa.Column('aspsp_country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('eb_account_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enablebanking_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enablebanking_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enablebanking_connections_state'), ['state'], unique=True)

    op.create_table('goal_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_progress_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_progress_id'), ['id'], unique=False)

    op.create_table('holding_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('kauf', 'verkauf', 'staking', 'dividende', name='lottype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_lots_id'), ['id'], unique=False)

    op.create_table('ignored_recurring_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'description_key', name='uq_ignored_recurring_account_desc')
    )
    with op.batch_alter_table('ignored_recurring_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ignored_recurring_payments_id'), ['id'], unique=False)

    op.create_table('paypal_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_id_encrypted', sa.String(), nullable=False),
    sa.Column('client_secret_encrypted', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paypal_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paypal_connections_id'), ['id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('categorized_at', sa.DateTime(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('receipt_filename', sa.String(), nullable=True),
    sa.Column('receipt_text', sa.Text(), nullable=True),
    sa.Column('receipt_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('import_hash', sa.String(), nullable=True),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_hash'), ['import_hash'], unique=False)

    op.create_table('vehicle_fuel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('full_tank', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_fuel_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_fuel_entries_id'), ['id'], unique=False)

    op.create_table('vehicle_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_goals_id'), ['id'], unique=False)

    op.create_table('vehicle_trip_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('match_field', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_trip_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_trip_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_trip_rules_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_vehicle', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('max_speed_kmh', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('start_location', sa.String(), nullable=True),
    sa.Column('end_location', sa.String(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.Column('odometer_start_km', sa.Float(), nullable=True),
    sa.Column('odometer_end_km', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('track_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'external_id', name='uq_vehicle_trip_external')
    )
    with op.batch_alter_table('vehicle_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_trips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_trips_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_trips_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('account_balance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('old_balance', sa.Float(), nullable=False),
    sa.Column('new_balance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_balance_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_balance_log_id'), ['id'], unique=False)

    op.create_table('business_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['business_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_issues_id'), ['id'], unique=False)

    op.create_table('category_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('suggested_category_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='categorysuggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'suggested_category_id', name='uq_category_suggestion_tx_cat')
    )
    with op.batch_alter_table('category_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_suggestions_id'), ['id'], unique=False)

    op.create_table('debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('interest_amount', sa.Float(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('is_extra_repayment', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debt_payments_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_payments_id'), ['id'], unique=False)

    op.create_table('goal_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('net_worth', 'account_balance', 'investment_value', 'savings_rate', 'custom_category_sum', 'debt_balance', name='goalmetrictype'), nullable=False),
    sa.Column('comparison', sa.Enum('gte', 'lte', name='goalcomparison'), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('scope_account_id', sa.Integer(), nullable=True),
    sa.Column('scope_asset_type', sa.Enum('aktie', 'etf', 'anleihe', 'krypto', 'sonstiges', name='assettype'), nullable=True),
    sa.Column('scope_category_id', sa.Integer(), nullable=True),
    sa.Column('scope_debt_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_window_months', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['scope_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['scope_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['scope_debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id')
    )
    with op.batch_alter_table('goal_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_triggers_id'), ['id'], unique=False)

    op.create_table('mail_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('mail_date', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('parsed_amount', sa.Float(), nullable=True),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parse_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'filename', name='uq_mail_attachment')
    )
    with op.batch_alter_table('mail_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('offen', 'laeuft', 'fertig', 'abgebrochen', name='mediastatus'), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_goal_id', sa.Integer(), nullable=True),
    sa.Column('linked_project_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['linked_project_id'], ['business_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_id'), ['id'], unique=False)

    op.create_table('return_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('remind_days_before', sa.Integer(), nullable=False),
    sa.Column('reminded', sa.Boolean(), nullable=False),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('return_deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_deadlines_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('fints_product_id', sa.String(), nullable=True),
    sa.Column('enablebanking_app_id', sa.String(), nullable=True),
    sa.Column('enablebanking_private_key_encrypted', sa.Text(), nullable=True),
    sa.Column('enablebanking_redirect_base_url', sa.String(), nullable=True),
    sa.Column('ollama_url', sa.String(), nullable=True),
    sa.Column('ollama_model', sa.String(), nullable=True),
    sa.Column('beleg_chat_model', sa.String(), nullable=True),
    sa.Column('sync_hour', sa.Integer(), nullable=False),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_hour', sa.Integer(), nullable=False),
    sa.Column('backup_retention', sa.Integer(), nullable=False),
    sa.Column('sparerpauschbetrag', sa.Float(), nullable=False),
    sa.Column('church_tax_rate', sa.Float(), nullable=False),
    sa.Column('marginal_tax_rate', sa.Float(), nullable=False),
    sa.Column('filing_married', sa.Boolean(), nullable=False),
    sa.Column('auto_categorize_enabled', sa.Boolean(), nullable=False),
    sa.Column('brave_search_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('websearch_provider', sa.String(), nullable=False),
    sa.Column('searxng_url', sa.String(), nullable=True),
    sa.Column('display_currency', sa.String(), nullable=False),
    sa.Column('residence_country', sa.String(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token_encrypted', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('telegram_last_update_id', sa.Integer(), nullable=True),
    sa.Column('n8n_webhook_secret_encrypted', sa.String(), nullable=True),
    sa.Column('native_sync_secret_encrypted', sa.String(), nullable=True),
    sa.Column('calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('twilio_account_sid', sa.String(), nullable=True),
    sa.Column('twilio_auth_token_encrypted', sa.String(), nullable=True),
    sa.Column('twilio_from_number', sa.String(), nullable=True),
    sa.Column('twilio_to_number', sa.String(), nullable=True),
    sa.Column('last_cashflow_alert_date', sa.Date(), nullable=True),
    sa.Column('last_budget_alert_month', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('nutrition_goal', sa.String(), nullable=False),
    sa.Column('nutrition_prefs', sa.String(), nullable=True),
    sa.Column('nutrition_kcal_target', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('immich_url', sa.String(), nullable=True),
    sa.Column('immich_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('immich_skip_confirm', sa.Boolean(), nullable=False),
    sa.Column('immich_quality_scan_page', sa.Integer(), nullable=False),
    sa.Column('ebay_app_id', sa.String(), nullable=True),
    sa.Column('ebay_cert_id_encrypted', sa.String(), nullable=True),
    sa.Column('ebay_ru_name', sa.String(), nullable=True),
    sa.Column('radicale_url', sa.String(), nullable=True),
    sa.Column('radicale_username', sa.String(), nullable=True),
    sa.Column('radicale_password_encrypted', sa.String(), nullable=True),
    sa.Column('radicale_calendar_url', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lon', sa.Float(), nullable=True),
    sa.Column('openroute_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('last_digest_sent_at', sa.DateTime(), nullable=True),
    sa.Column('transfers_marked_since_digest', sa.Integer(), nullable=False),
    sa.Column('morning_briefing_enabled', sa.Boolean(), nullable=False),
    sa.Column('morning_briefing_hour', sa.Integer(), nullable=False),
    sa.Column('morning_briefing_minute', sa.Integer(), nullable=False),
    sa.Column('morning_briefing_send_empty', sa.Boolean(), nullable=False),
    sa.Column('proactive_assistant_enabled', sa.Boolean(), nullable=False),
    sa.Column('proactive_assistant_min_gap_hours', sa.Integer(), nullable=False),
    sa.Column('proactive_assistant_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('proactive_assistant_last_hash', sa.String(), nullable=True),
    sa.Column('proactive_assistant_last_snapshot_hash', sa.String(), nullable=True),
    sa.Column('proactive_assistant_last_text', sa.String(), nullable=True),
    sa.Column('proactive_assistant_snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('ntfy_enabled', sa.Boolean(), nullable=False),
    sa.Column('ntfy_url', sa.String(), nullable=False),
    sa.Column('ntfy_topic', sa.String(), nullable=True),
    sa.Column('telegram_voice_replies', sa.Boolean(), nullable=False),
    sa.Column('ha_announce_enabled', sa.Boolean(), nullable=False),
    sa.Column('ha_announce_service', sa.String(), nullable=True),
    sa.Column('ha_announce_target', sa.String(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start_hour', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_end_hour', sa.Integer(), nullable=False),
    sa.Column('quiet_until', sa.DateTime(), nullable=True),
    sa.Column('midweek_checkin_enabled', sa.Boolean(), nullable=False),
    sa.Column('communication_style', sa.String(), nullable=False),
    sa.Column('mail_enabled', sa.Boolean(), nullable=False),
    sa.Column('imap_host', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_user', sa.String(), nullable=True),
    sa.Column('imap_password_encrypted', sa.String(), nullable=True),
    sa.Column('imap_folder', sa.String(), nullable=False),
    sa.Column('mail_last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('creditcard_mail_sender', sa.String(), nullable=True),
    sa.Column('creditcard_account_id', sa.Integer(), nullable=True),
    sa.Column('creditcard_debt_id', sa.Integer(), nullable=True),
    sa.Column('scalable_enabled', sa.Boolean(), nullable=False),
    sa.Column('scalable_last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('scalable_last_sync_status', sa.String(), nullable=True),
    sa.Column('scalable_space_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_set_at', sa.DateTime(), nullable=True),
    sa.Column('setup_completed_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret_encrypted', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('totp_recovery_code_hash', sa.String(), nullable=True),
    sa.Column('session_idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_locked_until', sa.DateTime(), nullable=True),
    sa.Column('homeassistant_url', sa.String(), nullable=True),
    sa.Column('homeassistant_token_encrypted', sa.String(), nullable=True),
    sa.Column('homeassistant_allowed_domains', sa.String(), nullable=True),
    sa.Column('homeassistant_allowed_areas', sa.String(), nullable=True),
    sa.Column('homeassistant_extra_services', sa.String(), nullable=True),
    sa.Column('homeassistant_require_confirmation', sa.Boolean(), nullable=False),
    sa.Column('homeassistant_dry_run', sa.Boolean(), nullable=False),
    sa.Column('homeassistant_wake_word', sa.String(), nullable=True),
    sa.Column('homeassistant_electricity_price', sa.Float(), nullable=False),
    sa.Column('homeassistant_history_entities', sa.String(), nullable=True),
    sa.Column('jarvis_memory_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creditcard_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['creditcard_debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['scalable_space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['business_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_id'), ['id'], unique=False)

    op.create_table('creditcard_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('mail_attachment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['mail_attachment_id'], ['mail_attachments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_creditcard_bill_message')
    )
    with op.batch_alter_table('creditcard_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditcard_bills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditcard_bills_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creditcard_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creditcard_bills_message_id'))
        batch_op.drop_index(batch_op.f('ix_creditcard_bills_id'))

    op.drop_table('creditcard_bills')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_id'))

    op.drop_table('time_entries')
    op.drop_table('settings')
    with op.batch_alter_table('return_deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_deadlines_id'))

    op.drop_table('return_deadlines')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_id'))

    op.drop_table('media_items')
    with op.batch_alter_table('mail_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_mail_attachments_id'))

    op.drop_table('mail_attachments')
    with op.batch_alter_table('goal_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_triggers_id'))

    op.drop_table('goal_triggers')
    with op.batch_alter_table('debt_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_payments_id'))
        batch_op.drop_index(batch_op.f('ix_debt_payments_debt_id'))

    op.drop_table('debt_payments')
    with op.batch_alter_table('category_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_suggestions_id'))

    op.drop_table('category_suggestions')
    with op.batch_alter_table('business_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_issues_id'))

    op.drop_table('business_issues')
    with op.batch_alter_table('account_balance_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_balance_log_id'))

    op.drop_table('account_balance_log')
    with op.batch_alter_table('vehicle_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_trips_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_trips_started_at'))
        batch_op.drop_index(batch_op.f('ix_vehicle_trips_id'))

    op.drop_table('vehicle_trips')
    with op.batch_alter_table('vehicle_trip_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_trip_rules_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_trip_rules_id'))

    op.drop_table('vehicle_trip_rules')
    with op.batch_alter_table('vehicle_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_goals_id'))

    op.drop_table('vehicle_goals')
    with op.batch_alter_table('vehicle_fuel_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_fuel_entries_id'))

    op.drop_table('vehicle_fuel_entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_import_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('paypal_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paypal_connections_id'))

    op.drop_table('paypal_connections')
    with op.batch_alter_table('ignored_recurring_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ignored_recurring_payments_id'))

    op.drop_table('ignored_recurring_payments')
    with op.batch_alter_table('holding_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_lots_id'))

    op.drop_table('holding_lots')
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_progress_id'))
        batch_op.drop_index(batch_op.f('ix_goal_progress_goal_id'))

    op.drop_table('goal_progress')
    with op.batch_alter_table('enablebanking_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enablebanking_connections_state'))
        batch_op.drop_index(batch_op.f('ix_enablebanking_connections_id'))

    op.drop_table('enablebanking_connections')
    with op.batch_alter_table('ebay_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebay_connections_state'))
        batch_op.drop_index(batch_op.f('ix_ebay_connections_id'))

    op.drop_table('ebay_connections')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_id'))

    op.drop_table('debts')
    with op.batch_alter_table('contract_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_reminders_id'))

    op.drop_table('contract_reminders')
    with op.batch_alter_table('business_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_projects_id'))

    op.drop_table('business_projects')
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_connections_id'))

    op.drop_table('bank_connections')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_id'))

    op.drop_table('trips')
    with op.batch_alter_table('savings_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_plans_id'))

    op.drop_table('savings_plans')
    with op.batch_alter_table('notified_anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notified_anomalies_key'))
        batch_op.drop_index(batch_op.f('ix_notified_anomalies_id'))

    op.drop_table('notified_anomalies')
    with op.batch_alter_table('net_worth_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshots_id'))

    op.drop_table('net_worth_snapshots')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_id'))

    op.drop_table('goals')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('bitvavo_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitvavo_connections_id'))

    op.drop_table('bitvavo_connections')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_owner_id'))
        batch_op.drop_index(batch_op.f('ix_spaces_id'))

    op.drop_table('spaces')
    with op.batch_alter_table('routine_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_runs_id'))

    op.drop_table('routine_runs')
    with op.batch_alter_table('passkey_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkey_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_passkey_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_passkey_credentials_credential_id'))

    op.drop_table('passkey_credentials')
    with op.batch_alter_table('meal_plan_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_entries_date'))

    op.drop_table('meal_plan_entries')
    with op.batch_alter_table('life_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_checkins_id'))

    op.drop_table('life_checkins')
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_rules_id'))

    op.drop_table('category_rules')
    with op.batch_alter_table('category_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_corrections_merchant_key'))
        batch_op.drop_index(batch_op.f('ix_category_corrections_id'))

    op.drop_table('category_corrections')
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_id'))

    op.drop_table('wishlist_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_uid'))
        batch_op.drop_index(batch_op.f('ix_todos_id'))

    op.drop_table('todos')
    with op.batch_alter_table('tax_tip_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_tip_status_year'))
        batch_op.drop_index(batch_op.f('ix_tax_tip_status_id'))

    op.drop_table('tax_tip_status')
    with op.batch_alter_table('sync_tombstones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_tombstones_space_id'))
        batch_op.drop_index(batch_op.f('ix_sync_tombstones_id'))
        batch_op.drop_index(batch_op.f('ix_sync_tombstones_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_tombstones_deleted_at'))

    op.drop_table('sync_tombstones')
    op.drop_table('smarthome_floorplan')
    with op.batch_alter_table('smarthome_automation_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smarthome_automation_drafts_id'))

    op.drop_table('smarthome_automation_drafts')
    with op.batch_alter_table('smarthome_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smarthome_aliases_id'))

    op.drop_table('smarthome_aliases')
    with op.batch_alter_table('smarthome_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smarthome_actions_id'))
        batch_op.drop_index(batch_op.f('ix_smarthome_actions_created_at'))

    op.drop_table('smarthome_actions')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_id'))

    op.drop_table('routines')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('proactive_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proactive_feedback_id'))
        batch_op.drop_index(batch_op.f('ix_proactive_feedback_created_at'))

    op.drop_table('proactive_feedback')
    with op.batch_alter_table('price_history_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_cache_id'))

    op.drop_table('price_history_cache')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_created_at'))

    op.drop_table('notification_log')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_id'))
        batch_op.drop_index(batch_op.f('ix_notes_entity_type'))
        batch_op.drop_index(batch_op.f('ix_notes_entity_id'))

    op.drop_table('notes')
    with op.batch_alter_table('life_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_areas_id'))

    op.drop_table('life_areas')
    op.drop_table('isin_ticker_cache')
    op.drop_table('immich_quality_flags')
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_metrics_id'))

    op.drop_table('health_metrics')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_uid'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_id'))

    op.drop_table('calendar_events')
    op.drop_table('basiszins_rates')
    with op.batch_alter_table('assistant_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_suggestions_id'))

    op.drop_table('assistant_suggestions')
    # ### end Alembic commands ###
